### PR TITLE
Passed RtVersionEye to Organizations, Teams and Projects

### PR DESCRIPTION
**Pull request by SherifWaly**
PR for #103

### CODE REVIEW

**Comment by SherifWaly** [comment]
@amihaiemil Please check this commit :)

**Review by amihaiemil — COMMENTED** [review]
@SherifWaly looks good! Can you leave a puzzle for continuing implementing those ``versionEye()`` methods?

**Comment by SherifWaly** [comment]
@amihaiemil I left a puzzle at RtVersionEye line 41 :)

**Comment by amihaiemil** [comment]
@rultor merge pls

**Pull request merged**
