### PR TITLE
Unit tests for RtMe

### PR DESCRIPTION
**Pull request by SherifWaly**
PR for #22

### CODE REVIEW

**Comment by SherifWaly** [comment]
@amihaiemil For Favorites and Comments I tested them in ``RtFavoritesTestCase`` and ``RtCommentsTestCase`` so is that good or I should test all methods in ``RtMeTestCase`` ?

**Comment by amihaiemil** [comment]
@SherifWaly No, I think we're good :)

**Review by amihaiemil — COMMENTED** [review]
@SherifWaly Looks good! :)

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@SherifWaly paid, thanks :)

**Comment by SherifWaly** [comment]
@amihaiemil Thanks :)

**Pull request merged**
