### PR TITLE
Unit tests for RepositoriesPage.

### PR DESCRIPTION
**Pull request by SherifWaly**
PR for #91

### CODE REVIEW

**Comment by SherifWaly** [comment]
@amihaiemil Please check this commit :)

**Comment by amihaiemil** [comment]
@SherifWaly Are you sure you commited all the repository pages mocks? I only see one :D

**Comment by SherifWaly** [comment]
@amihaiemil I left all the repositories in page1 and made an empty page2 only :D . Do you want to divide them on several page with limit < 30 ?

**Comment by amihaiemil** [comment]
@SherifWaly Should be fine, but where is ``repositoriespage1.json``? I only see ``repositoriespage2.json`` in the PR :D

**Comment by SherifWaly** [comment]
@amihaiemil It was included from before in resources :D

**Comment by amihaiemil** [comment]
@SherifWaly ah, I see now. Thanks

**Comment by amihaiemil** [comment]
@rultor merge pls

**Pull request merged**
