### PR TITLE
Implemented Favorites and Favorite.

### PR DESCRIPTION
**Pull request by SherifWaly**
PR for #20

### CODE REVIEW

**Comment by SherifWaly** [comment]
@amihaiemil Please check this commit :)

**Comment by amihaiemil** [comment]
@SherifWaly I'll have a look as soon as I get some time, hopefully today :D

**Review by amihaiemil — COMMENTED** [review]
@SherifWaly Looks good! Just please use RtFavorites in [RtUser.favorites()](https://github.com/decorators-squad/versioneye-api/blob/master/src/main/java/com/amihaiemil/versioneye/RtUser.java#L78) :)

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@rultor try to merge again...

**Comment by amihaiemil** [comment]
@SherifWaly I'm not sure what's wrong with rultor so I'll merge it maually..

**Pull request merged**
