### PR TITLE
Implemented MkJsonAuthenticated.

### PR DESCRIPTION
**Pull request by SherifWaly**
PR for #61

### CODE REVIEW

**Comment by SherifWaly** [comment]
@amihaiemil I ignored the test as I found that when calling ``JsonObjectBuilder.build()`` all the buffer is cleared and the ``JsonObjectBuilder`` becomes empty again. so at each build() call the old builder data should be saved but I don't find clone() method for example. What do you think about it :D ?

**Review by amihaiemil — COMMENTED** [review]
@SherifWaly looks good :D

**Comment by amihaiemil** [comment]
@SherifWaly Looks good, but a little more changes are needed to MKServer and MkVersionEye. I've opened issue https://github.com/decorators-squad/versioneye-api/issues/63, which I'll assign to you.

Leave this PR as it is, it's ok :)

**Comment by amihaiemil** [comment]
@rultor merge

**Pull request merged**
