### PR TITLE
Github API implementation.

### PR DESCRIPTION
**Pull request by SherifWaly**
PR for #81

### CODE REVIEW

**Comment by SherifWaly** [comment]
@amihaiemil Please check this commit :D 
I have left a puzzle for testing but if it's required I will add it :D

**Comment by SherifWaly** [comment]
@amihaiemil Please check this commit :D 
I have left a puzzle for testing but if it's required I will add it :D

**Comment by amihaiemil** [comment]
@SherifWaly No worries, it's ok.

Looks good, but can you add a puzzle to move the Repository fetch/paging stuff in a Repositories interface?

Github will be the entry point of the whole Github API and seeing the paging method there for instance (which refers only to paging of repos) looks strage. Also, it will be a little more complex than just that, because you can filter by org name, programming language etc. Specify that as well in the puzzle :D

**Comment by SherifWaly** [comment]
@amihaiemil As there is no default values in java so should we add another interface for example conditions which should be added to the Ctor. or how it would be done :D ?

**Comment by amihaiemil** [comment]
@SherifWaly Actually... I have no clue right now. 
The organization search should be on interface ``Organization``, clearly... so once the user has an Organization instance, he will do ``Organization.repositories()``, which will fetch all that orgs' Github repos.

The other few (lang, private etc), maybe they could be method arguments? Not sure, I'll think about it.

**Comment by amihaiemil** [comment]
@rultor merge

**Pull request merged**
