### PR TITLE
MkUsers, MkUser and unit tests

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #72 
Implemented mock for users API and signing up of users.
@SherifWaly You can have a look if you want :D

### CODE REVIEW

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by SherifWaly** [comment]
@amihaiemil The ``NewUser`` adds users that aren't authenticated or authenticated users should be added as a new user first as I find that there are 2 kinds of users in the storage :D ?

**Comment by amihaiemil** [comment]
@SherifWaly ``MkNewUser`` adds the regeistered user to the ``users`` node (these represent all of the users who have an account on VersionEye).

When ``MkUsers.user(...)`` is called, it is also checked if the user is found among the authenticated ones (an authenticated user is not written in the ``users`` node, since it doesn't make sense to have the same info in 2 places). If the user found is authenticated, only the ``fullName`` and ``userName`` are returned (this is the behaviour of the actual API). 

See [MkUsersTestCase](https://github.com/decorators-squad/versioneye-api/blob/master/src/test/java/com/amihaiemil/versioneye/MkUsersTestCase.java) for details on how the mock users are registered and read.

Makes sense?

**Comment by SherifWaly** [comment]
@amihaiemil Yes, I understand now thanks :)

**Pull request merged**
