### PR TITLE
Synchronized Storage

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #70 
@SherifWaly just so you know
Changes done:
for brevity and better semantics I renamed the following interfaces/classes:

``NfJsonObjectBuilder -> Storage``
``NfJsonObjectBuilderImpl -> MkStorage``

and added ``SyncStorage`` decorator.

### CODE REVIEW

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by SherifWaly** [comment]
@amihaiemil Thank you for keeping me updated :) 
I want to ask why rultor mentioned ``@jeff`` ? I think this is a bug that should be reported :D

**Comment by amihaiemil** [comment]
@SherifWaly yes, I think it's because I deleted my comment (``@rultor merge``) just before it replied... I had commented too early, forgot to remove the puzzle :D

**Comment by SherifWaly** [comment]
@amihaiemil Ok, I was just wondering why would it happen :D

**Pull request merged**
